<a href="https://colab.research.google.com/github/bilgekagansenol/SpamornotSpamproject/blob/main/spamornotspam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import nltk
nltk.download('punkt',force=True)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:

import pandas as pd
import os

file_path = r"/content/drive/MyDrive/spamornotspamproject/emails/emails.csv"
if os.path.isfile(file_path):
    print("folder is found")
else:
    print("path is wrong or folder is not exist")

folder is found

In [24]:
df = pd.read_csv(file_path)
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [25]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [26]:
df['tokenized_text'] = df['text'].apply(nltk.word_tokenize)

In [27]:
df.head()

,text,spam,tokenized_text
0,Subject: naturally irresistible your corporate...,1,"[Subject, :, naturally, irresistible, your, co..."
1,Subject: the stock trading gunslinger fanny i...,1,"[Subject, :, the, stock, trading, gunslinger, ..."
2,Subject: unbelievable new homes made easy im ...,1,"[Subject, :, unbelievable, new, homes, made, e..."
3,Subject: 4 color printing special request add...,1,"[Subject, :, 4, color, printing, special, requ..."
4,"Subject: do not have money , get software cds ...",1,"[Subject, :, do, not, have, money, ,, get, sof..."

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [29]:
import os
!git clone https://github.com/bilgekagansenol/SpamornotSpamproject

os.chdir('/content/SpamornotSpamproject')

Cloning into 'SpamornotSpamproject'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 43 (delta 19), reused 8 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (43/43), 230.96 KiB | 2.78 MiB/s, done.
Resolving deltas: 100% (19/19), done.

In [30]:
!ls

functions_cleaning_tokens.py  __pycache__	   SpamornotSpamproject
functions.ipynb		      spamornotspam.ipynb

In [31]:
import functions_cleaning_tokens

df['tokenized_text'] = df['tokenized_text'].apply(functions_cleaning_tokens.clean_tokens)
df.head()

,text,spam,tokenized_text
0,Subject: naturally irresistible your corporate...,1,"[subject, naturally, irresistible, your, corpo..."
1,Subject: the stock trading gunslinger fanny i...,1,"[subject, the, stock, trading, gunslinger, fan..."
2,Subject: unbelievable new homes made easy im ...,1,"[subject, unbelievable, new, homes, made, easy..."
3,Subject: 4 color printing special request add...,1,"[subject, color, printing, special, request, a..."
4,"Subject: do not have money , get software cds ...",1,"[subject, do, not, have, money, get, software,..."

In [32]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [40]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [37]:
pip install pyspellchecker

Collecting pyspellchecker
  Downloading pyspellchecker-0.8.1-py3-none-any.whl.metadata (9.4 kB)
Downloading pyspellchecker-0.8.1-py3-none-any.whl (6.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 42.4 MB/s eta 0:00:00
Installing collected packages: pyspellchecker
Successfully installed pyspellchecker-0.8.1

In [45]:
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from spellchecker import SpellChecker
import nltk

# Gerekli indirmeler
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Tanımlar
stopwords1 = stopwords.words('english')
lemmatizer = WordNetLemmatizer()
spell = SpellChecker()

def correct_spelling(tokens):
    return [spell.correction(token) for token in tokens]

def lemmatize_tokens(tokens):
    # Yazım hatalarını düzelt
    tokens = correct_spelling(tokens)
    # Stopwords kaldır
    tokens = [token for token in tokens if token not in stopwords1]
    # Lemmatization uygula
    return [lemmatizer.lemmatize(token) for token in tokens]

# Lemmatize işlemini uygula
df['tokenized_text'] = df['tokenized_text'].apply(correct_spelling)

print(df.head())

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

KeyboardInterrupt: